### ISSUE TITLE
How to solve undefined symbol: PyInt_FromLong?

### ISSUE THREAD

**Issue by b2220333** [liliangqi/person_search#9]
```
sam_train@sam-train-ubuntu1604:~/code/python/pytorch/pedestrian_detection/liliangqi_person_search$ python3 train.py
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    from models.model import SIPN
  File "/home/sam_train/code/python/pytorch/pedestrian_detection/liliangqi_person_search/models/model.py", line 16, in <module>
    from .strpn import STRPN
  File "/home/sam_train/code/python/pytorch/pedestrian_detection/liliangqi_person_search/models/strpn.py", line 17, in <module>
    from nms.pth_nms import pth_nms as nms
  File "/home/sam_train/code/python/pytorch/pedestrian_detection/liliangqi_person_search/nms/pth_nms.py", line 2, in <module>
    from ._ext import nms
  File "/home/sam_train/code/python/pytorch/pedestrian_detection/liliangqi_person_search/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: /home/sam_train/code/python/pytorch/pedestrian_detection/liliangqi_person_search/nms/_ext/nms/_nms.so: undefined symbol: PyInt_FromLong
sam_train@sam-train-ubuntu1604:~/code/python/pytorch/pedestrian_detection/liliangqi_person_search$ 
```

How to solve it?
Thank you~

**Comment by zt1112** [comment]
Have you solve the problem?
I got the same error.

**Comment by zt1112** [comment]
I have solved it.
Modify 'python' to 'python3' in setup.sh.

**Comment by b2220333** [comment]
Wow! You're great!! Solve this issue also for me.
